# Generated by Django 4.0.2 on 2022-02-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypost',
            name='content',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='categorypost',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
    ]
